title: "Shu Huang"
email: shuhuangucla@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://shushujie.github.io/" 
twitter_username: shuhuang17
github_username:  shushujie

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
